### ISSUE TITLE
add ../ to libsfx_dir

### ISSUE THREAD

**Issue by jeffythedragonslayer** [nikku4211/SNEsperiments#1]
I suggest adding another `../` to libsfx_dir in the makefiles.  If people clone this repo in C:\ and they also clone libSFX in C:\ they won't be able to build the SNESperiments without going up the correct number of directories in the makefiles.

**Comment by nikku4211** [comment]
I've added another `../`, does it work now?

**Comment by jeffythedragonslayer** [comment]
I had added them all on my local clone to get them all to build.  Probably would be easier to use a single makefile to build everything next time.

**Comment by nikku4211** [comment]
Removed the stray C.
